<?xml version="1.0" encoding="utf-8"?><Database Name="PTTS" Class="PBTSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\PTTS.mdf;Integrated Security=True" SettingsObjectName="PublicTransportTicketingSystem.My.MySettings" SettingsPropertyName="PTTSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Booking" Member="Bookings">
    <Type Name="Booking">
      <Column Name="bookingID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="customerIC" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="customerName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="customerContactNo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="ticketID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="employeeID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="bookingStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="totalPrice" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Employee_Booking" Member="Employee" ThisKey="employeeID" OtherKey="employeeID" Type="Employee" IsForeignKey="true" />
      <Association Name="Ticket_Booking" Member="Ticket" ThisKey="ticketID" OtherKey="ticketID" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employee" Member="Employees">
    <Type Name="Employee">
      <Column Name="employeeID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="employeeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="employeeIC" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="employeeContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="employeeEmail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Employee_Booking" Member="Bookings" ThisKey="employeeID" OtherKey="employeeID" Type="Booking" />
    </Type>
  </Table>
  <Table Name="dbo.LocationList" Member="LocationLists">
    <Type Name="LocationList">
      <Column Name="locationListID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="scheduleID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="locationID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="locationStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Location_LocationList" Member="Location" ThisKey="locationID" OtherKey="locationID" Type="Location" IsForeignKey="true" />
      <Association Name="Schedule_LocationList" Member="Schedule" ThisKey="scheduleID" OtherKey="scheduleID" Type="Schedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.promoteSchedule" Member="promoteSchedules">
    <Type Name="promoteSchedule">
      <Column Name="promoteScheduleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="promotionID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="scheduleID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="discountRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Promotion_promoteSchedule" Member="Promotion" ThisKey="promotionID" OtherKey="promotionID" Type="Promotion" IsForeignKey="true" />
      <Association Name="Schedule_promoteSchedule" Member="Schedule" ThisKey="scheduleID" OtherKey="scheduleID" Type="Schedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotion" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="promotionID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="promotionName" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="promotionStartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="promotionEndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="promotionDesc" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="promotionStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Promotion_promoteSchedule" Member="promoteSchedules" ThisKey="promotionID" OtherKey="promotionID" Type="promoteSchedule" />
    </Type>
  </Table>
  <Table Name="dbo.Seat" Member="Seats">
    <Type Name="Seat">
      <Column Name="seatID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="scheduleID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="seatStatus" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Seat_Ticket" Member="Tickets" ThisKey="seatID" OtherKey="seatID" Type="Ticket" />
      <Association Name="Schedule_Seat" Member="Schedule" ThisKey="scheduleID" OtherKey="scheduleID" Type="Schedule" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="ticketID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="seatID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="purchaseDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ticketPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ticketStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Ticket_Booking" Member="Bookings" ThisKey="ticketID" OtherKey="ticketID" Type="Booking" />
      <Association Name="Seat_Ticket" Member="Seat" ThisKey="seatID" OtherKey="seatID" Type="Seat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transport" Member="Transports">
    <Type Name="Transport">
      <Column Name="transportID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="seatPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="transportName" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="transportType" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="licensePlate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="totalSeat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tranportRow" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tranportColumn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="transportStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Transport_Schedule" Member="Schedules" ThisKey="transportID" OtherKey="transportID" Type="Schedule" />
    </Type>
  </Table>
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="locationID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="locationName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="locationType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="locationStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Location_LocationList" Member="LocationLists" ThisKey="locationID" OtherKey="locationID" Type="LocationList" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedules">
    <Type Name="Schedule">
      <Column Name="scheduleID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="departureDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estimateHours" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="transportID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="scheduleStatus" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Schedule_LocationList" Member="LocationLists" ThisKey="scheduleID" OtherKey="scheduleID" Type="LocationList" />
      <Association Name="Schedule_promoteSchedule" Member="promoteSchedules" ThisKey="scheduleID" OtherKey="scheduleID" Type="promoteSchedule" />
      <Association Name="Schedule_Seat" Member="Seats" ThisKey="scheduleID" OtherKey="scheduleID" Type="Seat" />
      <Association Name="Transport_Schedule" Member="Transport" ThisKey="transportID" OtherKey="transportID" Type="Transport" IsForeignKey="true" />
    </Type>
  </Table>
</Database>